### PR TITLE
Autoupdater

### PR DESCRIPTION
**Pull request by dragonmaus**
This conflicts heavily (entirely, actually) with your own implementation, but I'm making the PR anyway so that you have full freedom to decide what to do, even if I'm not immediately available.

### CODE REVIEW

**Comment by dragonmaus** [comment]
Of special note is the fact that the entire script is written in 100% PowerShell, and does not call any external utilities (e.g. `jq`).
I pulled in `lib/json.ps1` from the main bucket repo, so this adheres to the same JSON formatting standards as the main project.

**Comment by dragonmaus** [comment]
There are still some false negatives with the 64-bit detection (something to do with HTTP referer, I think), but that is much better than even a single false positive.

I'll have to fix it later though.

**Comment by kodybrown** [comment]
My update script was a quick and dirty little hack. I have no shame about it.. 😋 
But I definitely like your update script implementation. It is _much_ better!

I will merge it in and use it instead. Thanks! 👍🏼

**Comment by kodybrown** [comment]
Well, I'll have to merge this later. I think my IP address has been blocked by the host of nirsoft.net. It works on my phone, but not my computer. Too many downloads maybe. :)

**Comment by dragonmaus** [comment]
Hah. I haven't had that issue (yet?), but I am running into my computer blocking some of the .zip files because they "contain a virus". 😆

**Comment by dragonmaus** [comment]
I wasn't able to find any way around the "download twice" issue.
Basically, you have to choose between downloading one of the zip files twice (for a total of either two or three downloads per package, depending on whether or not there's a 64-bit version), or saving that zip file to disk and potentially triggering Windows Security, which will then block any access to the file. There doesn't seem to be any way to duplicate a stream in PowerShell.

**Comment by dragonmaus** [comment]
Closing this in favour of a cleaned-up and ready-to-merge branch.

**Pull request closed without merging**
